# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 21:38
from __future__ import unicode_literals

import apps.user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.user.models.UserManager()),
            ],
        ),
    ]
